---
- hosts: personal
  remote_user: root
  gather_facts: True
  tasks:
  - name: Get Linux cpuinfo Bogomips
    get_cpuinfo_test: 
    register: ansible_facts
  - debug: var=ansible_facts
  - name: Get IP addresses last 2 Octets
    setup: 
      filter: ansible_all_ipv4_addresses
  - debug: msg="{{ '.'.join(ansible_all_ipv4_addresses[0].split('.')[2:]) }}"